--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Point808/PMMP_Plugins
branches:
- master
projects:
  AdminMail:
    path: AdminMail/
  RealTime:
    path: RealTime/
  ASR:
    path: ASR/
...
