#name, main, version and api are required
name: RealTime
main: RealTime\MainClass
version: 2.1.3
api: [3.0.0, 4.0.0]
load: POSTWORLD
author: Guillaume351
description: Take control of the time


commands:
 rt:
  description: Lock the time
  usage: "Usage: /rt enable/sunrise/sunset/day/night/disable/lock"
  permission: realtime.command.rt
 hour:
  description: Get tell the hour
  usage: "Usage : /hour"
  permission: realtime.command.hour

  
  
permissions:
 realtime.command.rt:
  description: "Allows the user to run the rt command to control the time"
  default: op
 realtime.command.hour :
  description : "Allows the users to run the hour command to get tell the hour"
  default: true
